#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <juce_audio_devices/juce_audio_devices.h>

//==============================================================================
PedalForgeProcessor::PedalForgeProcessor()
    : AudioProcessor (BusesProperties()
                      .withInput  ("Input",    juce::AudioChannelSet::discreteChannels(8), true)
                      .withOutput ("Output",   juce::AudioChannelSet::discreteChannels(8), true)),
      presetManager (*this),
      midiLearn (graphEngine),
      playMidiLearn (playGraphEngine)
{
    graphEngine.onBoardConnectionsChanged = [this] {
        // Needs to happen asynchronously on the message thread because it opens hardware ports
        juce::MessageManager::callAsync ([this] {
            refreshHardwareMidiConnections();
        });
    };
}

PedalForgeProcessor::~PedalForgeProcessor()
{
    // Close all open hardware MIDI connections
    openMidiInputs.clear();
    const juce::ScopedLock sl (midiOutputLock);
    openMidiOutputs.clear();
}

//==============================================================================
void PedalForgeProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    graphEngine.prepare (sampleRate, samplesPerBlock,
                         getTotalNumInputChannels(),
                         getTotalNumOutputChannels());
                         
    playGraphEngine.prepare (sampleRate, samplesPerBlock,
                         getTotalNumInputChannels(),
                         getTotalNumOutputChannels());

    // Open hardware MIDI devices that the user has enabled in the Routing Tab
    refreshHardwareMidiConnections();
}

void PedalForgeProcessor::releaseResources()
{
    graphEngine.releaseResources();
    playGraphEngine.releaseResources();
}

bool PedalForgeProcessor::isBusesLayoutSupported (const BusesLayout& layouts) const
{
    // We support any layout up to 32 channels.
    // In standalone mode, this lets the user map all their hardware I/O freely.
    int totalIn = 0;
    for (auto& bus : layouts.inputBuses)
        totalIn += bus.size();

    int totalOut = 0;
    for (auto& bus : layouts.outputBuses)
        totalOut += bus.size();

    if (totalIn > 32 || totalOut > 32)
        return false;

    return true;
}

void PedalForgeProcessor::processBlock (juce::AudioBuffer<float>& buffer,
                                         juce::MidiBuffer& midiMessages)
{
    juce::ScopedNoDenormals noDenormals;

    // In Standalone mode, the JUCE wrapper's Audio/MIDI settings dialog allows the user
    // to globally enable MIDI inputs. We completely ignore these to prevent double-notes,
    // because PedalForge handles per-device MIDI routing internally.
    if (wrapperType == wrapperType_Standalone)
        midiMessages.clear();

    // (Global hardware MIDI mixing removed in favor of point-to-point Graph Nodes)

    // Process audio through the pedal graph and handle MIDI routing
    if (isPlayModeActive)
    {
        playMidiLearn.processMidi (midiMessages);
        playGraphEngine.processBlock (buffer, midiMessages);
    }
    else
    {
        midiLearn.processMidi (midiMessages);
        graphEngine.processBlock (buffer, midiMessages);
    }

    // Forward any MIDI generated by the graph to active hardware MIDI outputs
    {
        const juce::ScopedLock sl (midiOutputLock);
        juce::MidiBuffer extractedMidi;
        
        for (auto& output : openMidiOutputs)
        {
            if (output) 
            {
                extractedMidi.clear();
                if (isPlayModeActive)
                    playGraphEngine.extractHardwareMidi (output->getName(), extractedMidi);
                else
                    graphEngine.extractHardwareMidi (output->getName(), extractedMidi);
                    
                if (!extractedMidi.isEmpty())
                    output->sendBlockOfMessages (extractedMidi, juce::Time::getMillisecondCounterHiRes(), getSampleRate());
            }
        }
    }

    // Prevent the Standalone wrapper from double-sending MIDI to its globally selected outputs
    if (wrapperType == wrapperType_Standalone)
        midiMessages.clear();
}

//==============================================================================
juce::AudioProcessorEditor* PedalForgeProcessor::createEditor()
{
    return new PedalForgeEditor (*this);
}

//==============================================================================
void PedalForgeProcessor::getStateInformation (juce::MemoryBlock& destData)
{
    auto state = presetManager.serializeState();
    destData.replaceAll (state.toRawUTF8(),
                          state.getNumBytesAsUTF8());
}

void PedalForgeProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    auto state = juce::String::fromUTF8 (static_cast<const char*> (data),
                                          sizeInBytes);
    presetManager.restoreState (state);
}

//==============================================================================
// Hardware MIDI Connection Management
//==============================================================================
void PedalForgeProcessor::refreshHardwareMidiConnections()
{
    // Build sets of active device names by checking if their engineNodeId
    // appears in any board connection as a source or destination
    juce::StringArray activeInputs, activeOutputs;
    
    for (const auto& dev : graphEngine.getHardwareMidiDevices())
    {
        bool inUse = false;
        for (const auto& conn : graphEngine.getBoardConnections())
        {
            if (conn.srcNodeId == dev.engineNodeId || conn.dstNodeId == dev.engineNodeId)
            {
                inUse = true;
                break;
            }
        }
        
        if (inUse)
        {
            if (dev.isInput)  activeInputs.add  (dev.deviceName);
            else              activeOutputs.add (dev.deviceName);
        }
    }

    // --- Inputs ---
    // Remove any that are no longer active
    openMidiInputs.erase (
        std::remove_if (openMidiInputs.begin(), openMidiInputs.end(),
            [&] (const std::unique_ptr<juce::MidiInput>& mi) {
                return mi && !activeInputs.contains (mi->getName());
            }),
        openMidiInputs.end());

    // Open any newly-active inputs
    for (const auto& name : activeInputs)
    {
        bool alreadyOpen = false;
        for (auto& mi : openMidiInputs)
            if (mi && mi->getName() == name) { alreadyOpen = true; break; }

        if (!alreadyOpen)
        {
            for (const auto& info : juce::MidiInput::getAvailableDevices())
            {
                if (info.name == name)
                {
                    if (auto mi = juce::MidiInput::openDevice (info.identifier, this))
                    {
                        mi->start();
                        openMidiInputs.push_back (std::move (mi));
                    }
                    break;
                }
            }
        }
    }

    // --- Outputs ---
    {
        const juce::ScopedLock sl (midiOutputLock);
        openMidiOutputs.erase (
            std::remove_if (openMidiOutputs.begin(), openMidiOutputs.end(),
                [&] (const std::unique_ptr<juce::MidiOutput>& mo) {
                    return mo && !activeOutputs.contains (mo->getName());
                }),
            openMidiOutputs.end());

        for (const auto& name : activeOutputs)
        {
            bool alreadyOpen = false;
            for (auto& mo : openMidiOutputs)
                if (mo && mo->getName() == name) { alreadyOpen = true; break; }

            if (!alreadyOpen)
            {
                for (const auto& info : juce::MidiOutput::getAvailableDevices())
                {
                    if (info.name == name)
                    {
                        if (auto mo = juce::MidiOutput::openDevice (info.identifier))
                            openMidiOutputs.push_back (std::move (mo));
                        break;
                    }
                }
            }
        }
    }
}

//==============================================================================
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new PedalForgeProcessor();
}
