#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "dsp/PedalDesign.h"
#include <juce_audio_devices/juce_audio_devices.h>

//==============================================================================
PedalForgeProcessor::PedalForgeProcessor()
    : AudioProcessor (BusesProperties()
                      .withInput  ("Input",    juce::AudioChannelSet::discreteChannels(8), true)
                      .withOutput ("Output",   juce::AudioChannelSet::discreteChannels(8), true)),
      presetManager (*this),
      midiLearn (graphEngine),
      playMidiLearn (playGraphEngine)
{
    graphEngine.onBoardConnectionsChanged = [this] {
        // Needs to happen asynchronously on the message thread because it opens hardware ports
        juce::MessageManager::callAsync ([this] {
            refreshHardwareMidiConnections();
        });
    };
}

PedalForgeProcessor::~PedalForgeProcessor()
{
    // Close all open hardware MIDI connections
    openMidiInputs.clear();
    const juce::ScopedLock sl (midiOutputLock);
    for (auto& mo : openMidiOutputs)
    {
        if (mo)
        {
            auto outName = mo->getName();
            if (outName.containsIgnoreCase ("DAW")
                && (outName.containsIgnoreCase ("LCXL3")
                 || outName.containsIgnoreCase ("LC3")
                 || outName.containsIgnoreCase ("Launch Control")))
            {
                static const juce::uint8 dawOff[] = { 0x00, 0x20, 0x29, 0x02, 0x15, 0x02, 0x00 };
                mo->sendMessageNow (juce::MidiMessage::createSysExMessage (dawOff, sizeof (dawOff)));
            }
        }
    }
    openMidiOutputs.clear();
}

//==============================================================================
void PedalForgeProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    graphEngine.prepare (sampleRate, samplesPerBlock,
                         getTotalNumInputChannels(),
                         getTotalNumOutputChannels());
                         
    playGraphEngine.prepare (sampleRate, samplesPerBlock,
                         getTotalNumInputChannels(),
                         getTotalNumOutputChannels());

    // Open hardware MIDI devices that the user has enabled in the Routing Tab
    refreshHardwareMidiConnections();
    
    testSoundGen.prepare (sampleRate);
}

void PedalForgeProcessor::releaseResources()
{
    graphEngine.releaseResources();
    playGraphEngine.releaseResources();
}

bool PedalForgeProcessor::isBusesLayoutSupported (const BusesLayout& layouts) const
{
    // We support any layout up to 32 channels.
    // In standalone mode, this lets the user map all their hardware I/O freely.
    int totalIn = 0;
    for (auto& bus : layouts.inputBuses)
        totalIn += bus.size();

    int totalOut = 0;
    for (auto& bus : layouts.outputBuses)
        totalOut += bus.size();

    if (totalIn > 32 || totalOut > 32)
        return false;

    return true;
}

void PedalForgeProcessor::processBlock (juce::AudioBuffer<float>& buffer,
                                         juce::MidiBuffer& midiMessages)
{
    juce::ScopedNoDenormals noDenormals;

    testSoundGen.process (buffer);

    // In Standalone mode, the JUCE wrapper's Audio/MIDI settings dialog allows the user
    // to globally enable MIDI inputs. We completely ignore these to prevent double-notes,
    // because PedalForge handles per-device MIDI routing internally.
    if (wrapperType == wrapperType_Standalone)
        midiMessages.clear();

    // (Global hardware MIDI mixing removed in favor of point-to-point Graph Nodes)

    // Log host MIDI messages if present
    for (const auto meta : midiMessages)
    {
        auto msg = meta.getMessage();
        if (isPlayModeActive)
            playGraphEngine.logMidiMessage (msg, "Host MIDI");
        else
            graphEngine.logMidiMessage (msg, "Host MIDI");
    }

    // Process audio through the pedal graph and handle MIDI routing
    if (isPlayModeActive)
    {
        playMidiLearn.processMidi (midiMessages);
        playGraphEngine.processBlock (buffer, midiMessages);
    }
    else
    {
        midiLearn.processMidi (midiMessages);
        graphEngine.processBlock (buffer, midiMessages);
    }

    // Forward any MIDI generated by the graph to active hardware MIDI outputs
    {
        const juce::ScopedLock sl (midiOutputLock);
        juce::MidiBuffer extractedMidi;
        
        for (auto& output : openMidiOutputs)
        {
            if (output) 
            {
                extractedMidi.clear();
                if (isPlayModeActive)
                    playGraphEngine.extractHardwareMidi (output->getName(), extractedMidi);
                else
                    graphEngine.extractHardwareMidi (output->getName(), extractedMidi);
                    
                if (!extractedMidi.isEmpty())
                    output->sendBlockOfMessages (extractedMidi, juce::Time::getMillisecondCounterHiRes(), getSampleRate());
            }
        }
    }

    // Prevent the Standalone wrapper from double-sending MIDI to its globally selected outputs
    if (wrapperType == wrapperType_Standalone)
        midiMessages.clear();
}

//==============================================================================
juce::AudioProcessorEditor* PedalForgeProcessor::createEditor()
{
    return new PedalForgeEditor (*this);
}

//==============================================================================
void PedalForgeProcessor::getStateInformation (juce::MemoryBlock& destData)
{
    auto state = presetManager.serializeState();
    destData.replaceAll (state.toRawUTF8(),
                          state.getNumBytesAsUTF8());
}

void PedalForgeProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    auto state = juce::String::fromUTF8 (static_cast<const char*> (data),
                                          sizeInBytes);
    presetManager.restoreState (state);
}
//==============================================================================
// MIDI Input Callback
//==============================================================================
void PedalForgeProcessor::handleIncomingMidiMessage (juce::MidiInput* source,
                                                      const juce::MidiMessage& msg)
{
    if (source == nullptr) return;

    juce::MidiBuffer singleMsgBuf;
    singleMsgBuf.addEvent (msg, 0);

    if (isPlayModeActive)
        playMidiLearn.processMidi (singleMsgBuf);
    else
        midiLearn.processMidi (singleMsgBuf);

    graphEngine.injectHardwareMidi (source->getName(), msg);
    playGraphEngine.injectHardwareMidi (source->getName(), msg);

    graphEngine.logMidiMessage (msg, source->getName());
    playGraphEngine.logMidiMessage (msg, source->getName());

    // ── Navigation CCs: Page & Track buttons ──
    if (msg.isController())
    {
        int cc = msg.getControllerNumber();
        int val = msg.getControllerValue();
        auto& cfg = graphEngine.appMidiConfig;

        if (val > 64) // button pressed
        {
            if (cfg.pageLeftCC  != -1 && cc == cfg.pageLeftCC)  { graphEngine.cyclePage (-1); return; }
            if (cfg.pageRightCC != -1 && cc == cfg.pageRightCC) { graphEngine.cyclePage (1);  return; }
            if (cfg.trackLeftCC  != -1 && cc == cfg.trackLeftCC)  { graphEngine.cycleTrack (-1); return; }
            if (cfg.trackRightCC != -1 && cc == cfg.trackRightCC) { graphEngine.cycleTrack (1);  return; }
        }
    }

    // ── Auto-Map (Focus Pedal) ──
    if (graphEngine.appMidiConfig.novationMode == AppMidiConfig::NovationMode::AutoMap
        && msg.isController())
    {
        auto focusedId = graphEngine.getFocusedPedal();
        if (focusedId.uid == 0) return;

        // Reset slot assignments when focus changes
        if (focusedId.uid != autoMapLastFocusedNode)
        {
            autoMapCCSlots.clear();
            autoMapNextSlot = 0;
            autoMapLastFocusedNode = focusedId.uid;
        }

        // Find the focused pedal instance
        const PedalInstance* inst = nullptr;
        for (const auto& i : graphEngine.getPedalInstances())
        {
            if (i.nodeID == focusedId) { inst = &i; break; }
        }
        if (inst == nullptr || inst->design == nullptr) return;

        // Build ordered list of mappable parameters (knobs/sliders with mappings)
        // Only rebuild if needed — cache could be added later for performance
        struct MappableParam
        {
            juce::String controlID;
            juce::String paramID;  // JUCE AudioParameter ID (e.g. "3_gain")
        };
        std::vector<MappableParam> mappableParams;

        for (const auto& ctrl : inst->design->controls)
        {
            if (ctrl.type != "knob" && ctrl.type != "slider" && ctrl.type != "fader")
                continue;

            // Find the mapping for this control
            for (const auto& m : inst->design->mappings)
            {
                if (m.controlID == ctrl.controlID)
                {
                    mappableParams.push_back ({ ctrl.controlID, m.nodeParam });
                    break;
                }
            }
        }

        if (mappableParams.empty()) return;

        int cc = msg.getControllerNumber();
        float value = msg.getControllerValue() / 127.0f;

        // Assign this CC to a parameter slot if not already assigned
        auto slotIt = autoMapCCSlots.find (cc);
        int slotIndex = -1;

        if (slotIt != autoMapCCSlots.end())
        {
            slotIndex = slotIt->second;
        }
        else if (autoMapNextSlot < (int) mappableParams.size())
        {
            slotIndex = autoMapNextSlot++;
            autoMapCCSlots[cc] = slotIndex;
        }

        if (slotIndex < 0 || slotIndex >= (int) mappableParams.size())
            return;

        // Set the parameter value on the processor
        auto& mp = mappableParams[(size_t) slotIndex];

        if (auto* node = graphEngine.getGraph().getNodeForId (focusedId))
        {
            auto* proc = node->getProcessor();
            for (auto* param : proc->getParameters())
            {
                if (auto* rp = dynamic_cast<juce::RangedAudioParameter*> (param))
                {
                    if (rp->getParameterID() == mp.paramID)
                    {
                        rp->setValueNotifyingHost (value);
                        break;
                    }
                }
            }
        }
    }
}

//==============================================================================
// Hardware MIDI Connection Management
//==============================================================================
void PedalForgeProcessor::refreshHardwareMidiConnections()
{
    // Helper: detect any Novation Launch Control variant
    auto isNovationLC = [] (const juce::String& name) -> bool
    {
        return name.containsIgnoreCase ("Launch Control")
            || name.containsIgnoreCase ("LCXL3")
            || name.containsIgnoreCase ("LC3");
    };

    // Helper: detect if a port is a Novation DAW port (needs SysEx handshake)
    auto isNovationDAWPort = [] (const juce::String& name) -> bool
    {
        return name.containsIgnoreCase ("DAW")
            && (name.containsIgnoreCase ("LCXL3")
             || name.containsIgnoreCase ("LC3")
             || name.containsIgnoreCase ("Launch Control"));
    };

    // Build sets of active device names by checking if their engineNodeId
    // appears in any board connection as a source or destination
    juce::StringArray activeInputs, activeOutputs;
    
    for (const auto& dev : graphEngine.getHardwareMidiDevices())
    {
        bool inUse = false;
        for (const auto& conn : graphEngine.getBoardConnections())
        {
            if (conn.srcNodeId == dev.engineNodeId || conn.dstNodeId == dev.engineNodeId)
            {
                inUse = true;
                break;
            }
        }
        
        // Always open: all inputs, Novation LC devices (for DAW mode handshake),
        // and any device with an active routing connection
        bool isNov = isNovationLC (dev.deviceName);
        if (inUse || dev.isInput || isNov)
        {
            if (dev.isInput)  activeInputs.add  (dev.deviceName);
            else              activeOutputs.add (dev.deviceName);
            DBG ("PedalForge: Active MIDI device: " + dev.deviceName + (dev.isInput ? " (input)" : " (output)") + (isNov ? " [Novation]" : ""));
        }
    }

    // --- Inputs ---
    // Remove any that are no longer active
    openMidiInputs.erase (
        std::remove_if (openMidiInputs.begin(), openMidiInputs.end(),
            [&] (const std::unique_ptr<juce::MidiInput>& mi) {
                return mi && !activeInputs.contains (mi->getName());
            }),
        openMidiInputs.end());

    // Open any newly-active inputs
    for (const auto& name : activeInputs)
    {
        bool alreadyOpen = false;
        for (auto& mi : openMidiInputs)
            if (mi && mi->getName() == name) { alreadyOpen = true; break; }

        if (!alreadyOpen)
        {
            for (const auto& info : juce::MidiInput::getAvailableDevices())
            {
                if (info.name == name)
                {
                    if (auto mi = juce::MidiInput::openDevice (info.identifier, this))
                    {
                        mi->start();
                        openMidiInputs.push_back (std::move (mi));
                    }
                    break;
                }
            }
        }
    }

    // --- Outputs ---
    {
        const juce::ScopedLock sl (midiOutputLock);
        openMidiOutputs.erase (
            std::remove_if (openMidiOutputs.begin(), openMidiOutputs.end(),
                [&] (const std::unique_ptr<juce::MidiOutput>& mo) {
                    bool shouldRemove = mo && !activeOutputs.contains (mo->getName());
                    if (shouldRemove)
                    {
                        // Send DAW mode off when disconnecting a Novation DAW port
                        if (isNovationDAWPort (mo->getName()))
                        {
                            static const juce::uint8 dawOff[] = { 0x00, 0x20, 0x29, 0x02, 0x15, 0x02, 0x00 };
                            mo->sendMessageNow (juce::MidiMessage::createSysExMessage (dawOff, sizeof (dawOff)));
                        }
                    }
                    return shouldRemove;
                }),
            openMidiOutputs.end());

        for (const auto& name : activeOutputs)
        {
            bool alreadyOpen = false;
            for (auto& mo : openMidiOutputs)
                if (mo && mo->getName() == name) { alreadyOpen = true; break; }

            if (!alreadyOpen)
            {
                for (const auto& info : juce::MidiOutput::getAvailableDevices())
                {
                    if (info.name == name)
                    {
                        if (auto mo = juce::MidiOutput::openDevice (info.identifier))
                        {
                            // Send DAW mode on when opening a Novation DAW port
                            if (isNovationDAWPort (info.name))
                            {
                                DBG ("PedalForge: Enabling DAW mode on: " + info.name);

                                // Method 1: Note message — works for all Novation MK3 controllers
                                // Note On, channel 16 (0x9F), note 12 (0x0C), velocity 127 (0x7F)
                                mo->sendMessageNow (juce::MidiMessage::noteOn (16, 12, (juce::uint8) 127));

                                // Method 2: SysEx — LCXL3 (device ID 0x15)
                                static const juce::uint8 dawOnXL[] = { 0x00, 0x20, 0x29, 0x02, 0x15, 0x02, 0x7F };
                                mo->sendMessageNow (juce::MidiMessage::createSysExMessage (dawOnXL, sizeof (dawOnXL)));

                                // Method 3: SysEx — LC3 (device ID 0x14)
                                static const juce::uint8 dawOnLC[] = { 0x00, 0x20, 0x29, 0x02, 0x14, 0x02, 0x7F };
                                mo->sendMessageNow (juce::MidiMessage::createSysExMessage (dawOnLC, sizeof (dawOnLC)));
                            }
                            else
                            {
                                DBG ("PedalForge: Opened MIDI output: " + info.name);
                            }
                            openMidiOutputs.push_back (std::move (mo));
                        }
                        break;
                    }
                }
            }
        }
    }
}

//==============================================================================
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new PedalForgeProcessor();
}
